sudo: false
dist: bionic
language: go
os:
  - linux
  - osx
osx_image: xcode11
go:
  - 1.15.x
  - 1.16.x
before_install:
  - export GO111MODULE=on
install:
  - go get -u golang.org/x/lint/golint
  - export golint=$(go list -f {{.Target}} golang.org/x/lint/golint)
  - go mod vendor


script:
  - golint .
  - go test -v ./... --bench=. -cover